### ISSUE TITLE
As a student, I want to pull up my class schedule, so I can see my class schedule on my phone

### ISSUE THREAD

**Issue by XiangweiChen** [cse442-spring-2020-offering/cse442-semester-project-skr-2-0#2]
Add class to schedule and view it in weekly-view
### Acceptance Test

- [x] The schedule will highlight the correct area when the user adds a class. (bug fixed)

- [x] add edge cases such as :

- [x]  notify the user if their inputs are empty (such as Class name, Class Room, Start time, End time)

- [x] notify the user if the end time is earlier than the start time 

- [x] notify the user if the end time is the same as the start time

- [x] notify the user if the end time and the start time exceed the time limit

**Comment by XiangweiChen** [comment]
Acceptance Test

1. On the login page, there are two text boxes that you can type in labeled "username" and "password" and one login button that let you to home page

2. The calendar will be on the main page, it can be defaulted to a random calendar, or empty
