### ISSUE TITLE
Task #1 input page

### ISSUE THREAD

**Issue by JerryLee0323** [cse442-spring-2020-offering/cse442-semester-project-skr-2-0#23]
Have a page with functioning user input where they input their calendar and the calendar gets updated.

### Task Tests:

- [x] After submitting the input page, the calendar highlights the time interval requested by user input.
- [x] The users are able to type class name, class begin-time and class end-time. (range: 8:00 - 21:00)
- [x] After submitting the input page, the calendar highlights the time interval requested by user input.
- [x] Make sure that the program does not crash if users input invalid input(5:00, 500).
- [ ] Make sure that the highlighted area does not disappear after going to other pages.
