### ISSUE TITLE
Task#2 Make the schedule in weekly view (From Monday to Sunday) 

### ISSUE THREAD

**Issue by XiangweiChen** [cse442-spring-2020-offering/cse442-semester-project-skr-2-0#25]
### Task Tests

- [x] the schedule shows calendar from Monday to Sunday

- [x] the timeline of the schedule will be from 8 am. to 9 p.m.

- [x] the user is able to click on the box that indicates the time period

**Comment by ProfMatthewHz** [comment]
Thanks for the assignment offer, but I prefer to leave this work to the group ;)
