### ISSUE TITLE
Task #3 Make the print button functional 

### ISSUE THREAD

**Issue by XiangweiChen** [cse442-spring-2020-offering/cse442-semester-project-skr-2-0#26]
### Task Tests

- [x] Make sure the print button sends the request to print

- [x] The print button will take you to print option page

- [x] The print option page will show the sample of the schedule page
