### ISSUE TITLE
task# 5 Buttons for forget, register button and remember me check box

### ISSUE THREAD

**Issue by zchen52** [cse442-spring-2020-offering/cse442-semester-project-skr-2-0#27]
### Task Tests

- [x] There will be a Forget button and a Register button

- [x] There will be a remember me checkbox, that allow you to check and uncheck

- [x] When the user clicks on the register button, this will take you to the register page

- [x] The register page will not have functionalities yet
