### ISSUE TITLE
Task #4 add function for exams

### ISSUE THREAD

**Issue by JerryLee0323** [cse442-spring-2020-offering/cse442-semester-project-skr-2-0#28]
Takes in input and prints the input after clicking the "Add" button in Exams

### Task test:

- [x]  Submit button on add/edit page only submits when the input field isn't empty.

- [x]  Clicking the submit field with inputs will show what you inputted in the field

- [x] Submit button does not work on invalid year (not 4 digits, not valid characters, before 2020)

- [x]  Submit button does not work on invalid date (not 2 digits, not valid characters, before 30 or 31)

- [x]  Submit button does not work on invalid month (not 2 digits, not valid characters, between 1 and 12)
