### ISSUE TITLE
Task 5 - Implement login function

### ISSUE THREAD

**Issue by soap231** [cse442-spring-2020-offering/cse442-semester-project-skr-2-0#52]
### Task Test: 
- [x]  After registering an account, he/she can log in using that account.
- [x]  The app should output a warning message when either username or password is invalid.
- [ ]  Account should store schedule information
